* CentOS Linux release 8.1.1911 (Core) 
  I made two installations: OpenMPI and MVAPICH.  I would recommend
  the OpenMPI version, since that is what is used at almost all other
  installations.  There was some concern that the OpenMPI version was
  buggy, but that seems not to be the case.  I am keeping the notes
  here in case it is useful to others.

* gcc openmpi
** module
  module load cpu gcc/10.2.0 openmpi/4.0.4 gmp/6.1.2 mpfr/4.0.2 cmake/3.18.2 openblas/dynamic/0.3.7
  Already loaded cpu, gcc/10.2.0

** boost
  # UPDATE: Maybe we can just do this:
  module load boost/1.74.0
  # OLD instructions:
  wget https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.tar.bz2
  tar -jxf boost_1_74_0.tar.bz2 
  cd boost_1_74_0
  ./bootstrap.sh --prefix=$HOME/gnu_openmpi/install --without-libraries=python
  ./b2 --prefix=$HOME/gnu_openmpi/install -j 64
  ./b2 --prefix=$HOME/gnu_openmpi/install install
  
** Elemental
   git clone https://gitlab.com/bootstrapcollaboration/elemental.git
   cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 -DCMAKE_INSTALL_PREFIX=$HOME/gnu_openmpi/install -DMATH_LIBS="-L$BLASDIR -lopenblas"

** libarchive
   wget http://www.libarchive.org/downloads/libarchive-3.5.1.tar.xz
   ./configure --prefix=$HOME/gnu_openmpi/install

** RapidJSON
   git clone https://github.com/Tencent/rapidjson.git
   cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_INSTALL_PREFIX=$HOME/gnu_openmpi/install

** sdpb
   git clone https://github.com/davidsd/sdpb.git
   CXX=mpicxx ./waf configure --prefix=$HOME/gnu_openmpi/install --elemental-dir=$HOME/gnu_openmpi/install --rapidjson-dir=$HOME/gnu_openmpi/install --boost-dir=$HOME/gnu_openmpi/install  --libarchive-dir=$HOME/gnu_openmpi/install 

** Trilinos
   git clone --branch trilinos-release-12-12-branch https://github.com/trilinos/Trilinos.git
   cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=gfortran -DTrilinos_ENABLE_Sacado=ON -DTrilinos_ENABLE_Kokkos=OFF -DTrilinos_ENABLE_Teuchos=OFF -DCMAKE_INSTALL_PREFIX=$HOME/gnu_openmpi/install ..

** scalar_blocks
   git clone https://gitlab.com/bootstrapcollaboration/scalar_blocks
   ./waf configure --boost-dir=$HOME/gnu_openmpi/install --gmp-dir=$HOME/gnu_openmpi/install --trilinos-dir=$HOME/gnu_openmpi/install --eigen-incdir=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/intel-19.1.1.217/eigen-3.3.7-plaog3szjnn3gh6wq5co55xxjuswwo7f/include/eigen3 --prefix=$HOME/gnu_openmpi/install

** fmt
   wget https://github.com/fmtlib/fmt/releases/download/6.2.1/fmt-6.2.1.zip
   unzip fmt-6.2.1.zip
   cd fmt-6.2.1
   mkdir build
   cd build
   cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=$HOME/gnu_openmpi/install ..
   make
   make install
** blocks_3d
   module load boost/1.74.0
   git clone https://gitlab.com/bootstrapcollaboration/blocks_3d
   ./waf configure --prefix=$HOME/gnu_openmpi/install --fmt-dir=$HOME/gnu_openmpi/install --fmt-libdir=$HOME/gnu_openmpi/install/lib64 --boost-dir=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/gcc-10.2.0/boost-1.74.0-ubdskthwa2edpqy4bx6deq6c3qy2xubs/include --eigen-incdir=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/intel-19.1.1.217/eigen-3.3.7-plaog3szjnn3gh6wq5co55xxjuswwo7f/include/eigen3
   ./waf
   ./waf install

* Batch Scripts
  /home/wlandry/gnu_openmpi/runs/TTTT_small.sh
  /home/wlandry/gnu_openmpi/runs/blocks.sh

* gcc mvapich
** module
   module load cpu gcc/10.2.0 mvapich2/2.3.4 gmp/6.1.2 mpfr/4.0.2 cmake/3.18.2 openblas/dynamic/0.3.7

** boost
  wget https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2
  tar -jxf boost_1_74_0.tar.bz2 
  cd boost_1_74_0
  ./bootstrap.sh --prefix=$HOME/gnu_mvapich/install --without-libraries=python
  ./b2 --prefix=$HOME/gnu_mvapich/install -j 64
  ./b2 --prefix=$HOME/gnu_mvapich/install install
  
** Elemental
   git clone https://gitlab.com/bootstrapcollaboration/elemental.git
   cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 -DCMAKE_INSTALL_PREFIX=$HOME/gnu_mvapich/install -DMATH_LIBS="-L$BLASDIR -lopenblas"

** libarchive
   wget http://www.libarchive.org/downloads/libarchive-3.5.1.tar.xz
   ./configure --prefix=$HOME/gnu_mvapich/install

** RapidJSON
   git clone https://github.com/Tencent/rapidjson.git
   cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_INSTALL_PREFIX=$HOME/gnu_mvapich/install

** sdpb
   git clone https://github.com/davidsd/sdpb.git
   CXX=mpicxx ./waf configure --prefix=$HOME/gnu_mvapich/install --elemental-dir=$HOME/gnu_mvapich/install --rapidjson-dir=$HOME/gnu_mvapich/install --boost-dir=$HOME/gnu_mvapich/install  --libarchive-dir=$HOME/gnu_mvapich/install 

** Trilinos
   git clone --branch trilinos-release-12-12-branch https://github.com/trilinos/Trilinos.git
   cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=gfortran -DTrilinos_ENABLE_Sacado=ON -DTrilinos_ENABLE_Kokkos=OFF -DTrilinos_ENABLE_Teuchos=OFF -DCMAKE_INSTALL_PREFIX=$HOME/gnu_mvapich/install

** scalar_blocks
   git clone https://gitlab.com/bootstrapcollaboration/scalar_blocks
   ./waf configure --boost-dir=$HOME/gnu_mvapich/install --gmp-dir=$HOME/gnu_mvapich/install --trilinos-dir=$HOME/gnu_mvapich/install --eigen-incdir=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/intel-19.1.1.217/eigen-3.3.7-plaog3szjnn3gh6wq5co55xxjuswwo7f/include/eigen3 --prefix=$HOME/gnu_mvapich/install

** fmt
   wget https://github.com/fmtlib/fmt/releases/download/6.2.1/fmt-6.2.1.zip
   cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=$HOME/gnu_mvapich/install
** blocks_3d
   git clone https://gitlab.com/bootstrapcollaboration/blocks_3d
   ./waf configure --prefix=$HOME/gnu_mvapich/install --fmt-dir=$HOME/gnu_mvapich/install --fmt-libdir=$HOME/gnu_mvapich/install/lib64 --boost-dir=$HOME/gnu_mvapich/install --eigen-incdir=/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen2/intel-19.1.1.217/eigen-3.3.7-plaog3szjnn3gh6wq5co55xxjuswwo7f/include/eigen3

** Batch scripts
  /home/wlandry/gnu_mvapich/runs/TTTT_small.sh

